version: '3.3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  vcode2:
    image: vcode2
    ports:
      - "8088:8088"
    links:
      - redis:redis_server
    environment:
        - GIN_MODE=release
    restart: always
